language: cpp

matrix:
  include:
    - name: Test Docker based on Ubuntu 18.04 LTS + gcc
      os: linux
      dist: trusty
      sudo: required
      services: docker
      script:
        - sh Scripts/travis_build_docker.sh
    - name: Test OS X 10.14 + Xcode 10.2 + clang
      os: osx
      osx_image: xcode10.2
      compiler: clang
      script:
        - sh Scripts/travis_build.sh
  before_install:
    - eval "${MATRIX_EVAL}"