jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - template: Scripts/azure_pipelines_build_windows.yml
- job: Linux
  pool:
    vmImage: 'Ubuntu-18.04'
  steps:
  - template: Scripts/azure_pipelines_build_linux.yml
